-- RLOOP-043 (Draft)
-- Replay quarantine control plane persistence + audit + purge helpers.
-- NOTE: This is a design draft. Review before production apply.

create table if not exists public.replay_quarantine_messages (
  replay_id text primary key,
  event_id text not null,
  dedup_key text,
  route text not null,
  status text not null default 'pending_review',
  quarantine_reason text not null,
  replay_count integer not null,
  last_error_classification text,
  last_error_message text,
  failed_at timestamptz,
  quarantined_at timestamptz not null,
  reviewed_at timestamptz,
  reviewed_by text,
  redriven_at timestamptz,
  dropped_at timestamptz,
  payload jsonb,
  headers jsonb,
  original_dead_letter jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint replay_quarantine_messages_status_check
    check (status in ('pending_review', 'redriven', 'dropped'))
);

create index if not exists idx_replay_quarantine_messages_status_quarantined_at
  on public.replay_quarantine_messages (status, quarantined_at desc);

create index if not exists idx_replay_quarantine_messages_route_status
  on public.replay_quarantine_messages (route, status);

create table if not exists public.replay_quarantine_audit_log (
  id bigint generated by default as identity primary key,
  replay_id text not null references public.replay_quarantine_messages(replay_id),
  action text not null,
  actor_id text not null,
  reason text not null,
  approval_ref text not null,
  request_id text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  constraint replay_quarantine_audit_action_check
    check (action in ('quarantined', 'manual_redrive_requested', 'force_drop_requested', 'status_changed'))
);

create index if not exists idx_replay_quarantine_audit_log_replay_created
  on public.replay_quarantine_audit_log (replay_id, created_at desc);

create or replace function public.replay_quarantine_messages_status_guard()
returns trigger
language plpgsql
as $$
begin
  if old.status in ('redriven', 'dropped') and new.status <> old.status then
    raise exception 'terminal quarantine status cannot transition (% -> %)', old.status, new.status;
  end if;

  if old.status = 'pending_review' and new.status = 'redriven' then
    new.redriven_at = coalesce(new.redriven_at, now());
  end if;

  if old.status = 'pending_review' and new.status = 'dropped' then
    new.dropped_at = coalesce(new.dropped_at, now());
  end if;

  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_replay_quarantine_messages_status_guard on public.replay_quarantine_messages;
create trigger trg_replay_quarantine_messages_status_guard
before update on public.replay_quarantine_messages
for each row execute function public.replay_quarantine_messages_status_guard();

create or replace function public.replay_quarantine_audit_log_immutable_guard()
returns trigger
language plpgsql
as $$
begin
  raise exception 'replay_quarantine_audit_log is immutable (% not allowed)', tg_op;
end;
$$;

drop trigger if exists trg_replay_quarantine_audit_log_no_update on public.replay_quarantine_audit_log;
create trigger trg_replay_quarantine_audit_log_no_update
before update on public.replay_quarantine_audit_log
for each row execute function public.replay_quarantine_audit_log_immutable_guard();

drop trigger if exists trg_replay_quarantine_audit_log_no_delete on public.replay_quarantine_audit_log;
create trigger trg_replay_quarantine_audit_log_no_delete
before delete on public.replay_quarantine_audit_log
for each row execute function public.replay_quarantine_audit_log_immutable_guard();

-- Purge draft (run in controlled batch job):
-- delete from public.replay_quarantine_messages
-- where status in ('redriven', 'dropped')
--   and coalesce(reviewed_at, updated_at, quarantined_at) < now() - interval '90 days';
