#!/usr/bin/env bash
set -euo pipefail

# RLOOP-048 draft harness
# Purpose: run DB-near atomicity checks with controlled failpoints in an ephemeral schema.
#
# Required env:
#   DATABASE_URL        Postgres connection string
# Optional env:
#   HARNESS_SCHEMA      Override schema name
#   HARNESS_DRY_RUN=1   Print SQL only
#
# Output: JSON lines (one per scenario)

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL is required" >&2
  exit 1
fi

SCHEMA="${HARNESS_SCHEMA:-rloop048_$(date +%s)}"
DRY_RUN="${HARNESS_DRY_RUN:-0}"

read -r -d '' SQL <<'EOSQL' || true
\set ON_ERROR_STOP on

create schema if not exists :schema_name;
set search_path to :schema_name, public;

create table if not exists replay_quarantine_messages (
  replay_id text primary key,
  status text not null,
  reviewed_at timestamptz,
  updated_at timestamptz,
  redriven_at timestamptz,
  dropped_at timestamptz
);

create table if not exists replay_quarantine_audit_log (
  id bigint generated by default as identity primary key,
  replay_id text not null,
  action text not null,
  request_id text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  unique (replay_id, action, request_id)
);

create or replace function replay_quarantine_apply_admin_action_fi(
  p_replay_id text,
  p_action text,
  p_request_id text,
  p_failpoint text default null
)
returns table(replay_id text, final_status text, deduped boolean)
language plpgsql
as $$
declare
  v_target_status text;
  v_inserted text;
begin
  v_target_status := case when p_action = 'manual_redrive_requested' then 'redriven' else 'dropped' end;

  insert into replay_quarantine_audit_log (replay_id, action, request_id, metadata)
  values (p_replay_id, p_action, p_request_id, jsonb_build_object('idempotency_gate', true))
  on conflict (replay_id, action, request_id) do nothing
  returning replay_id into v_inserted;

  if v_inserted is null then
    return query select p_replay_id, v_target_status, true;
    return;
  end if;

  if p_failpoint = 'audit_insert_fail' then
    raise exception 'injected audit failure' using errcode = 'XX001';
  end if;

  update replay_quarantine_messages
     set status = v_target_status,
         reviewed_at = now(),
         updated_at = now()
   where replay_id = p_replay_id
     and status = 'pending_review';

  if not found then
    raise exception 'stale transition' using errcode = 'P0001';
  end if;

  if p_failpoint = 'state_transition_fail' then
    raise exception 'injected state transition failure' using errcode = 'XX002';
  end if;

  insert into replay_quarantine_audit_log (replay_id, action, request_id, metadata)
  values (p_replay_id, 'status_changed', p_request_id, jsonb_build_object('toStatus', v_target_status));

  return query select p_replay_id, v_target_status, false;
end;
$$;

insert into replay_quarantine_messages (replay_id, status, reviewed_at, updated_at)
values ('r-ok', 'pending_review', null, now())
on conflict (replay_id) do update set status = excluded.status;

insert into replay_quarantine_messages (replay_id, status, reviewed_at, updated_at)
values ('r-audit-fail', 'pending_review', null, now())
on conflict (replay_id) do update set status = excluded.status;

insert into replay_quarantine_messages (replay_id, status, reviewed_at, updated_at)
values ('r-state-fail', 'pending_review', null, now())
on conflict (replay_id) do update set status = excluded.status;

-- happy path
select json_build_object(
  'scenario','happy_path',
  'result', (select row_to_json(t) from replay_quarantine_apply_admin_action_fi('r-ok','manual_redrive_requested','req-1', null) t limit 1),
  'state_after', (select status from replay_quarantine_messages where replay_id='r-ok'),
  'audit_rows', (select count(*) from replay_quarantine_audit_log where replay_id='r-ok')
);

-- failpoint: audit insert fail => tx rollback; state must remain pending_review
begin;
select replay_quarantine_apply_admin_action_fi('r-audit-fail','manual_redrive_requested','req-2','audit_insert_fail');
rollback;

select json_build_object(
  'scenario','audit_insert_fail',
  'state_after', (select status from replay_quarantine_messages where replay_id='r-audit-fail'),
  'gate_rows', (select count(*) from replay_quarantine_audit_log where replay_id='r-audit-fail' and request_id='req-2')
);

-- failpoint: state transition fail => tx rollback; state + audit must remain unchanged
begin;
select replay_quarantine_apply_admin_action_fi('r-state-fail','manual_redrive_requested','req-3','state_transition_fail');
rollback;

select json_build_object(
  'scenario','state_transition_fail',
  'state_after', (select status from replay_quarantine_messages where replay_id='r-state-fail'),
  'gate_rows', (select count(*) from replay_quarantine_audit_log where replay_id='r-state-fail' and request_id='req-3')
);

drop schema if exists :schema_name cascade;
EOSQL

if [[ "$DRY_RUN" == "1" ]]; then
  echo "$SQL"
  exit 0
fi

psql "$DATABASE_URL" \
  -v schema_name="$SCHEMA" \
  -qAt \
  -c "$SQL" \
  | grep -E '^\{.*\}$' || true
